SHOW GLOBAL VARIABLES LIKE 'local_infile';

#Enable local infile
SET GLOBAL local_infile=ON;

LOAD DATA LOCAL INFILE 'C:\Users\PC Home\Desktop\Eduard\IT Academy\CURS ANALISIS DADES\SPRINT4\companies.csv'
INTO TABLE bussines.company
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:\Users\PC Home\Desktop\Eduard\IT Academy\CURS ANALISIS DADES\SPRINT4\products.csv'
INTO TABLE bussines.product
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:\Users\PC Home\Desktop\Eduard\IT Academy\CURS ANALISIS DADES\SPRINT4\credit_cards.csv'
INTO TABLE bussines.credit_card
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:\Users\PC Home\Desktop\Eduard\IT Academy\CURS ANALISIS DADES\SPRINT4\user_ca.csv'
INTO TABLE bussines.user
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:\Users\PC Home\Desktop\Eduard\IT Academy\CURS ANALISIS DADES\SPRINT4\user_uk.csv'
INTO TABLE bussines.user
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:\Users\PC Home\Desktop\Eduard\IT Academy\CURS ANALISIS DADES\SPRINT4\user_usa.csv'
INTO TABLE bussines.user
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:\Users\PC Home\Desktop\Eduard\IT Academy\CURS ANALISIS DADES\SPRINT4\transactions.csv'
INTO TABLE bussines.trasnaction
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;